var xauth=new (function(){this.getAvailableServices=function(b){for(i=0;i<b.length;i++);return[]};this.checkServices=function(b,a){XAuth.retrieve({retrieve:b.map(function(c){return OPENLIKE.Sources[c].xauth}),callback:function(c){var d=b.map(function(j){if(c.tokens[OPENLIKE.Sources[j].xauth])return j});a.call(null,d)}})}});
if(!window.OPENLIKE)window.OPENLIKE={assetHost:document.location.href.match(/localhost/)?"http://localhost/~justin/openlike":"http://openlike.org",util:{update:function(){for(var b=arguments[0],a=1,c=arguments.length,d;a<c;a++)for(d in arguments[a])if(arguments[a].hasOwnProperty(d))b[d]=arguments[a][d];return b},escape:function(b){return(b==null?"":b).toString().replace(/[<>"&\\]/g,function(a){switch(a){case "<":return"&lt;";case ">":return"&gt;";case '"':return'"';case "&":return"&amp;";case "\\":return"\\\\";
default:return a}})},notundef:function(b,a){return typeof b=="undefined"?a:b},hasClass:function(b,a){return b.className.match(new RegExp("\\b"+a+"\\b"))?true:false},addClass:function(b,a){if(OPENLIKE.util.hasClass(b,a))return false;b.className+=" "+a;return true},removeClass:function(b,a){if(!OPENLIKE.util.hasClass(b,a))return false;b.className=b.className.replace(new RegExp("\\b"+a+"\\b"));return true},toggleClass:function(b,a){return OPENLIKE.util.hasClass(b,a)?OPENLIKE.util.removeClass(b,a):OPENLIKE.util.addClass(b,
a)},serialize:function(b,a){var c=[];a=OPENLIKE.util.update({separator:"&",join:"=",urlencode:true},a?a:{});for(prop in b)if(b.hasOwnProperty(prop)){var d=a.urlencode?encodeURIComponent(prop):prop,j=a.urlencode?encodeURIComponent(b[prop]):b[prop];c.push(d+a.join+j)}return c.join(a.separator)}}};
OPENLIKE.buildWidget=function(b){function a(g){if(b.css){n=document.createElement("LINK");n.rel="stylesheet";n.type="text/css";n.href=b.css;(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(n)}var h=document.getElementsByTagName("SCRIPT");h=h[h.length-1];k=document.createElement("DIV");k.id="openlike-widget";k.className=b.editable?"openlike clearfix edit":"openlike clearfix";k.setAttribute("data-vertical",b.vertical);if(b.header){o=document.createElement("P");o.innerHTML=OPENLIKE.util.escape(b.header);
k.appendChild(o)}p=document.createElement("UL");d=0;for(j=b.s.length;d<j;d++)if(e=OPENLIKE.Sources[b.s[d]]){e=OPENLIKE.prepSource(b.s[d],e);q=document.createElement("LI");if(e.html)f=e.html(b);else{f=document.createElement("A");f.className=e.klass;g.indexOf(e.name)>-1&&OPENLIKE.util.addClass(f,"enabled");f.setAttribute("data-service",e.name);f.href="#";f.innerHTML=OPENLIKE.util.escape(e.name);if(e.title)f.title=e.title;if(e.basicLink){f.href=e.basicLink(f,b);f.target=e.target}f.onclick=function(m){return function(l){var t=
document.getElementById("openlike-widget");if(!localStorage.openlike&&!b.editable){OPENLIKE.UI.openEditor(b.vertical);l.preventDefault();return false}else typeof console!="undefined"&&console.log("prefs already stored",localStorage.openlike);if(OPENLIKE.util.hasClass(t,"edit")&&b.editable){OPENLIKE.util.toggleClass(this,"enabled");OPENLIKE.util.addClass(document.getElementById("openlike-edit-btn"),"enabled");l.preventDefault();return false}if(m.popup){window.open(this.href,m.popup.target,m.popup.attrs);
l.preventDefault();return false}return true}}(e)}q.appendChild(f);p.appendChild(q)}k.appendChild(p);if(b.editable){g=document.createElement("a");g.id="openlike-edit-btn";g.onclick=function(){if(OPENLIKE.util.hasClass(this,"enabled")){OPENLIKE.UI.updateServicePreferences();OPENLIKE.util.removeClass(this,"enabled")}};g.appendChild(document.createTextNode("Save "+b.vertical+" Preferences"));h.parentNode.insertBefore(g,h.nextSibling)}h.parentNode.insertBefore(k,h);k=o=p=q=h=e=null}var c=function(){for(var g=
{},h,m=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),l=0;l<m.length;l++){h=m[l].split("=");g[h[0]]=decodeURIComponent(h[1])}return g}(),d,j,k,o,p,q,f,e,n;b=OPENLIKE.util.update({editable:false,url:document.location.href,title:document.title,vertical:"default",header:"Like this:",css:OPENLIKE.assetHost+"/v1/openlike.css",s:OPENLIKE.Verticals[c.vertical&&c.vertical!=""?c.vertical:"default"]},c,b);c=OPENLIKE.Preferences.get(b.vertical);var r=xauth.getAvailableServices(b.s),
s=OPENLIKE.Verticals[b.vertical]?OPENLIKE.Verticals[b.vertical]:OPENLIKE.Verticals["default"];if(c.length)a(c);else r.length?xauth.checkServices(r,function(g){g.length?a(g):a(s)}):a(s)};
OPENLIKE.prepSource=function(b,a){a=OPENLIKE.util.update({},a);a.name=b;a.target=OPENLIKE.util.notundef(a.target,"_blank");a.klass="openlike-"+OPENLIKE.util.escape(b);if(a.popup){if(typeof a.popup!="object")a.popup={};a.popup.target=OPENLIKE.util.notundef(a.popup.target,"_blank");a.popup.attrs=OPENLIKE.util.notundef(a.popup.attrs,"width=360,height=360")}return a};
OPENLIKE.Verticals={news:["facebook","twitter","google","yahoo","reddit"],movie:["facebook","twitter","blockbuster","netflix","hunch"],"default":["google","facebook","hunch","digg","reddit","stumbleupon"]};
OPENLIKE.Sources={digg:{url:"http://digg.com/",basicLink:function(b,a){var c=encodeURIComponent(a.url),d=encodeURIComponent(a.title);return"http://digg.com/submit?phase=2&url="+c+"&title="+d},title:"Like this on Digg"},facebook:{url:"http://facebook.com",basicLink:function(b,a){var c=encodeURIComponent(a.url),d=encodeURIComponent(a.title);return"http://www.facebook.com/sharer.php?u="+c+"&t="+d}},google:{url:"http://google.com",basicLink:function(b,a){var c=encodeURIComponent(a.url);return"http://www.google.com/buzz/post?message="+
encodeURIComponent("I like this... "+a.title)+"&url="+c},title:"Like this on Google Buzz",xauth:"googxauthdemo.appspot.com"},hunch:{url:"http://hunch.com",basicLink:function(b,a){var c=encodeURIComponent(a.url),d=encodeURIComponent(a.title),j=a.type?"&category="+encodeURIComponent(a.type):"";return"http://hunch.com/openlike/?url="+c+"&title="+d+j},title:"Add this to your Hunch taste profile"},reddit:{url:"http://reddit.com/",basicLink:function(b,a){var c=encodeURIComponent(a.url),d=encodeURIComponent(a.title);
return"http://www.reddit.com/submit?url="+c+"&title="+d},title:"Like this on Reddit"},stumbleupon:{url:"http://www.stumbleupon.com/",basicLink:function(b,a){return"http://www.stumbleupon.com/submit?url="+encodeURIComponent(a.url)},title:"Like this on StumbleUpon"},yahoo:{url:"http://search.yahoo.com/",basicLink:function(b,a){return"http://search.yahoo.com/search?p="+encodeURIComponent(a.title)+"&fr=orion&ygmasrchbtn=Web+Search"},title:"Search this on Yahoo Buzz!"},blockbuster:{url:"http://www.blockbuster.com/",
basicLink:function(b,a){return"http://www.blockbuster.com/search/product/products?keyword="+encodeURIComponent(a.title)},title:"Search this on Blockbuster"},netflix:{url:"http://www.netflix.com/",basicLink:function(b,a){return"http://www.netflix.com/WiSearch?oq=&v1="+encodeURIComponent(a.title)+"&search_submit="},title:"Search this on Netflix"},twitter:{url:"http://twitter.com",basicLink:function(b,a){return"http://twitter.com/home?status="+encodeURIComponent("I like this: "+a.url+" #openlike")},
title:"Tweet this like"}};
OPENLIKE.Preferences=new (function(){this.getStorage=function(){return localStorage.openlike?JSON.parse(localStorage.openlike):{}};this.get=function(b){var a=OPENLIKE.Preferences.getStorage();return a[b]?a[b]:[]};this.put=function(b,a){var c=OPENLIKE.Preferences.getStorage();c[b]=a;localStorage.openlike=JSON.stringify(c);return true};this.show=function(b,a){var c=OPENLIKE.Preferences.get(b);if(c.indexOf(a)==-1){c.push(a);return OPENLIKE.Preferences.put(b,c)}return false};this.hide=function(b,a){var c=
OPENLIKE.Preferences.get(b),d;if((d=c.indexOf(a))>-1){c.splice(d,1);return OPENLIKE.Preferences.put(b,c)}return false}});
OPENLIKE.UI=new (function(){this.openEditor=function(b){window.open(OPENLIKE.assetHost+"/edit.html?vertical="+encodeURIComponent(b),"OPENLIKE_Editor","width=600,height=300,menubar=no,location=no,resizable=no,scrollbars=no,status=no")};this.updateServicePreferences=function(){for(var b=document.getElementById("openlike-widget"),a=[],c=b.getAttribute("data-vertical"),d=0;d<b.childNodes[1].childNodes.length;d++)a.push(b.childNodes[1].childNodes[d].childNodes[0]);for(d=0;d<a.length;d++){b=a[d];var j=
OPENLIKE.util.hasClass(b,"enabled");OPENLIKE.Preferences[j?"show":"hide"](c,b.getAttribute("data-service"))}}});
